#
# ~/.zshenv
#

# Add a bin dir inside home to the PATH
typeset -U path
path=(~/bin $path[@])

# Set vim as the default editor
export EDITOR=nvim

# Set git environment
export GIT_AUTHOR_NAME="nbonfils"
export GIT_AUTHOR_EMAIL="nils.bonfils@epfl.ch"
export GIT_COMMITTER_NAME=$GIT_AUTHOR_NAME
export GIT_COMMITTER_EMAIL=$GIT_AUTHOR_EMAIL

# XDG to prevent firefox from creating "Desktop" dir
export XDG_DESKTOP_DIR="$HOME"

# Set the GOPATH
#export GOPATH=$(go env GOPATH)

# Set the Android Dev related environment
#export ANDROID_HOME=$HOME/Android/Sdk
#path+=($ANDROID_HOME/tools $ANDROID_HOME/tools/bin $ANDROID_HOME/platform-tools)
#export PATH
