# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=/home/nature/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
#ZSH_THEME="robbyrussell"
ZSH_THEME="spaceship"

# Spaceship theme specific configuration
    # PROMPT
    SPACESHIP_PROMPT_ADD_NEWLINE=true
    SPACESHIP_PROMPT_SEPARATE_LINE=true
    SPACESHIP_PROMPT_TRUNC=3

    # CHAR
    SPACESHIP_CHAR_SYMBOL='➔'
    
    # PREFIXES
    SPACESHIP_PREFIX_SHOW=true
    SPACESHIP_PREFIX_HOST=' at '
    SPACESHIP_PREFIX_DIR=' in '
    SPACESHIP_PREFIX_GIT=' on '
    SPACESHIP_PREFIX_ENV_DEFAULT=' via '
    SPACESHIP_PREFIX_NVM=$SPACESHIP_PREFIX_ENV_DEFAULT
    SPACESHIP_PREFIX_RUBY=$SPACESHIP_PREFIX_ENV_DEFAULT
    SPACESHIP_PREFIX_XCODE=$SPACESHIP_PREFIX_ENV_DEFAULT
    SPACESHIP_PREFIX_SWIFT=$SPACESHIP_PREFIX_ENV_DEFAULT
    SPACESHIP_PREFIX_VENV=$SPACESHIP_PREFIX_ENV_DEFAULT
    
    # GIT
    SPACESHIP_GIT_SHOW=true
    SPACESHIP_GIT_UNCOMMITTED='+'
    SPACESHIP_GIT_UNSTAGED='!'
    SPACESHIP_GIT_UNTRACKED='?'
    SPACESHIP_GIT_STASHED='$'
    SPACESHIP_GIT_UNPULLED='⇣'
    SPACESHIP_GIT_UNPUSHED='⇡'
    
    # NVM
    SPACESHIP_NVM_SHOW=true
    SPACESHIP_NVM_SYMBOL='⬢'
    
    # RUBY
    SPACESHIP_RUBY_SHOW=true
    SPACESHIP_RUBY_SYMBOL='💎'
    
    # SWIFT
    SPACESHIP_SWIFT_SHOW_LOCAL=true
    SPACESHIP_SWIFT_SHOW_GLOBAL=false
    SPACESHIP_SWIFT_SYMBOL='🐦'
    
    # XCODE
    SPACESHIP_XCODE_SHOW_LOCAL=true
    SPACESHIP_XCODE_SHOW_GLOBAL=false
    SPACESHIP_XCODE_SYMBOL='🛠'
    
    # VENV
    SPACESHIP_VENV_SHOW=true
    
    # VI_MODE
    SPACESHIP_VI_MODE_SHOW=true
    SPACESHIP_VI_MODE_INSERT="[I]"
    SPACESHIP_VI_MODE_NORMAL="[N]"

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git colorize)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

####################
# Aliases
####################
alias su='su -'
alias updatemirrors='curl "https://www.archlinux.org/mirrorlist/?country=CH&country=FR&protocol=https&ip_version=4&use_mirror_status=on" > /home/nature/tempo19026HHH && sed -i "s/^#Server/Server/" /home/nature/tempo19026HHH && sudo mv /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.prev && sudo mv /home/nature/tempo19026HHH /etc/pacman.d/mirrorlist'
alias vpnblazebone='sudo openvpn /home/nature/.blazebone/vpn/fw1-udp-1194-nils-config.ovpn'
alias vpnepfl='sudo openconnect -u nbonfils vpn.epfl.ch'
alias diff='diff --color=auto'
alias sshlivebox='ssh -p 4500 -N -L 3000:localhost:4501 pi@schoolhelp.internet-box.ch'
alias ssh='TERM=xterm-256color ssh'
alias ru='setxkbmap ru'
alias фр='setxkbmap ch fr'
#alias tank='mount -t nfs cloud.blazebone.com:/tank/ ~/tank'

# Display a csv file
# column -s, -t < epfl/pcml/project/Train/train.csv | less -#2 -N -S
