# History
HISTFILE=~/.histfile
HISTSIZE=32000
SAVEHIST=32000

# History search
autoload -Uz up-line-or-beginning-search down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

[[ -n "$key[Up]" ]] && bindkey -- "$key[Up]" up-line-or-beginning-search
[[ -n "$key[Down]" ]] && bindkey -- "$key[Down]" down-line-or-beginning-search

# Various options
setopt appendhistory notify COMPLETE_ALIASES
unsetopt beep

# Vi-like key bindings
bindkey -v

# Completion
zstyle :compinstall filename '/home/nature/.zshrc'
zstyle ':completion:*' menu select
zstyle ':completion::complete:*' gain-privileges 1

autoload -Uz compinit
compinit

# Prompt
# Only load Liquid Prompt in interactive shells, not from a script or from scp
[[ $- = *i* ]] && source ~/dotfiles/liquidprompt/liquidprompt


#########
# Aliases
#########
alias su='su -'
alias updatemirrors='curl "https://www.archlinux.org/mirrorlist/?country=CH&country=FR&protocol=https&ip_version=4&use_mirror_status=on" > /home/nature/tempo19026HHH && sed -i "s/^#Server/Server/" /home/nature/tempo19026HHH && sudo mv /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.prev && sudo mv /home/nature/tempo19026HHH /etc/pacman.d/mirrorlist'
alias vpnblazebone='sudo openvpn /home/nature/.blazebone/vpn/fw1-udp-1194-nils-config.ovpn'
alias vpnepfl='sudo openconnect -u nbonfils vpn.epfl.ch'
alias diff='diff --color=auto'
alias sshlivebox='ssh -p 4500 -N -L 3000:localhost:4501 pi@schoolhelp.internet-box.ch'
alias ssh='TERM=xterm-256color ssh'
alias ru='setxkbmap ru'
alias фр='setxkbmap ch fr'
#alias tank='mount -t nfs cloud.blazebone.com:/tank/ ~/tank'

# Display a csv file
# column -s, -t < epfl/pcml/project/Train/train.csv | less -#2 -N -S
